fail_fast: false
default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: debug-statements
      - id: check-ast
      - id: check-json
      - id: detect-private-key
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=100]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [ --line-length=100 ]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        exclude: ^venv/ ^.git/ ^.idea/ ^.DS_Store/ ^.ipynb_checkpoints
        args: [--max-line-length=100,
               --disable=no-name-in-module, # pylint has some issues understanding dataclasses
               --disable=no-member,
               --disable=import-error,
               --disable=missing-class-docstring,
               --disable=missing-function-docstring,  # some classes/functions are self-explanatory
               --disable=too-few-public-methods,
               --disable=syntax-error]  # E0001: Parsing failed: 'invalid syntax ...'

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.1.1
    hooks:
    -   id: autoflake

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'mypy "$@" || true' --
        language: system
        types: [python]
        exclude: ^venv/ ^.git/ ^.idea/ ^.DS_Store/ ^.ipynb_checkpoints/
